### ISSUE TITLE
[Bug]: Unable to generate openapi spec

### ISSUE THREAD

**Issue by prashanth-hegde** [ballerina-platform/ballerina-dev-tools#229]
### Description

Unable to create an openapi spec as specified in the help docs here 
https://ballerina.io/learn/openapi-tool/ 

### Steps to Reproduce

```shell
bal new -t service hello_service
cd hello_service
bal build 
bal openapi -i service.bal -o api.yml
```

Get the below error 
```shell
[I] [hello_service] bal openapi -i service.bal -o api.yml
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-05-22 10:37:01,705] SEVERE {b7a.log.crash} - Format specifier '%s' 
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.base/java.util.Formatter.format(Formatter.java:2672)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at io.ballerina.openapi.converter.diagnostic.ExceptionDiagnostic.<init>(ExceptionDiagnostic.java:38)
        at io.ballerina.openapi.cmd.OASContractGenerator.generateOAS3DefinitionsAllService(OASContractGenerator.java:137)
        at io.ballerina.openapi.cmd.OpenApiCmd.ballerinaToOpenApi(OpenApiCmd.java:231)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:195)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)

```

### Source (service.bal)
```bal
import ballerina/http;

# A service representing a network-accessible API
# bound to port `9090`.
service / on new http:Listener(9090) {

    # A resource for generating greetings
    # + name - the input string name
    # + return - string name with hello message or error
    resource function get greeting(string name) returns string|error {
        // Send a response back to the caller.
        if name is "" {
            return error("name should not be empty!");
        }
        return "Hello, " + name;
    }
}

```

### Affected Version(s)

MacOs Ventura 13.2.1 M1 (aarch64)

```shell
[I] [hello_service] bal version 
Ballerina 2201.5.0 (Swan Lake Update 5)
Language specification 2022R4
Update Tool 1.3.14
```

### Related area

-> API Docs

**Comment by anupama-pathirage** [comment]
This is fixed in latest latest version. 
It gives `ERROR [:(1:1,1:1)] Failed to generate OpenAPI definition due to: /Volumes/data/review/hellowrld/api.yml/service_openapi.yaml (No such file or directory)`

You can issue the command `bal openapi -i service.bal` or `bal openapi -i service.bal -o output`
